name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.webp'

jobs:
  deploy:
    env:
  
    # This maps the GitHub Secret to an Environment Variable the script can see
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      NEW_RELIC_APP_NAME: "Online-Image-Lab"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          # Define them here for the runner
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_APP_NAME: "Online-Image-Lab"
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          # IMPORTANT: List which variables to send to the VPS
          envs: NEW_RELIC_LICENSE_KEY,NEW_RELIC_APP_NAME
          script: |
            set -e
            cd /home/ubuntu/image-lab
            git fetch origin
            git reset --hard origin/main
            chmod +x deploy.sh
            ./deploy.sh
