name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.webp'

jobs:
  deploy:
    env:
  
    # This maps the GitHub Secret to an Environment Variable the script can see
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      NEW_RELIC_APP_NAME: "Online-Image-Lab"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            
            # 1. Go to folder
            cd /home/ubuntu/image-lab
            
            # 2. Update the code (including the deploy.sh script itself!)
            git fetch origin
            git reset --hard origin/main
            
            # 3. Make sure the script is executable (just in case)
            chmod +x deploy.sh
            
            # 4. Run the script
            ./deploy.sh
